message("Welcome Aaki's build config.")

set(ENV{AAKI_CFG.BUILD_PATH} ${CMAKE_BINARY_DIR})

set(EXECUTABLE_OUTPUT_PATH $ENV{AAKI_CFG.BUILD_PATH}/bin CACHE PATH "Build directory" FORCE)
set(LIBRARY_OUTPUT_PATH $ENV{AAKI_CFG.BUILD_PATH}/lib CACHE PATH "Build directory" FORCE)
set(CMAKE_CACHEFILE_DIR $ENV{AAKI_CFG.BUILD_PATH}/cache CACHE PATH "Build directory" FORCE)

set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${EXECUTABLE_OUTPUT_PATH} CACHE PATH "Build directory" FORCE)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${LIBRARY_OUTPUT_PATH} CACHE PATH "Build directory" FORCE)

message("EXECUTABLE_OUTPUT_PATH : " ${EXECUTABLE_OUTPUT_PATH})
message("LIBRARY_OUTPUT_PATH : " ${LIBRARY_OUTPUT_PATH})
message("CMAKE_CACHEFILE_DIR : " ${CMAKE_CACHEFILE_DIR})